apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-disk
  annotations:
    volume.alpha.kubernetes.io/storage-class: "yes"
  labels:
    name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

